name: Test

on: 
  pull_request: {}
  push:
    branches: "*"
    tags: "*"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with pip
        run: |
          pip install ."[test]"
      - run: isort --diff .
      - run: black --check .
      - run: flake8

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t image:test
      
      - name: Test docker image
        run: |
          cp .env.example .env
          docker run --rm -d --name server -p --env-file .env 5000:5000 image:test
          sleep 5
          curl --fail localhost:5000
          docker kill server
          docker run  --env-file .env image:test pytest --cov .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Create repository if it doesn't exist yet
        run: aws ecr describe-repositories --repository-names ${{ github.repository }} || aws ecr create-repository --repository-name ${{ github.repository }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 614871946825.dkr.ecr.us-east-1.amazonaws.com #${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: latest
        run: |
          docker tag image:test $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
